app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('items.urls', namespace='items')),
]

items/urls.py
from django.urls import path
from .views import Home, Details, add_to_cart, CartSummary, remove_from_cart, remove_row, Checkout, UserProfile, AddProduct, completion
from django.conf.urls.static import static
from django.conf import settings

app_name = 'items'

urlpatterns = [
    path('', Home.as_view(), name='home'), 
    path('product/<slug>/', Details.as_view(), name='details'),
    path('cart/<slug>', add_to_cart, name="cart"),
    path('cart_summary', CartSummary.as_view(), name='cart_summary'),
    path('profile', UserProfile.as_view(), name='profile'),
    path('checkout', Checkout.as_view(), name='checkout'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove_from_cart'),
    path('remove-row/<slug>', remove_row, name='remove_row'),
    path('completion', completion, name='completion'),
    path('add-product', AddProduct.as_view(), name='add_product')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORIES = (
        ('T', 'Technology'),
        ('C', 'Comedy'),
        ('A', 'Adventure'),
        ('H', 'Horror'),
        ('R', 'Romance'),
        ('O', 'Other'),
        ('M', 'Mystery')
)

class Product(models.Model):
    ProductID = models.AutoField(primary_key=True)    
    ProductName = models.CharField(max_length=100)
    Price = models.FloatField()
    Discount = models.FloatField(blank=True, null=True)
    Description = models.TextField()
    Image = models.ImageField(default = 'default.png')
    Stock = models.IntegerField(default=1)
    slug = models.SlugField()
    UserID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ProductType = models.CharField(choices=CATEGORIES, max_length=1)

    def get_absolute_url(self):
        return reverse("items:details", kwargs={
                'slug': self.slug
        })

    def get_cart_url(self):
        return reverse("items:cart", kwargs={
                'slug': self.slug
        })

    def get_final_price(self):
        if self.Discount == 0:
            return round(self.Price, 2)
        else:
            return round(self.Price - self.Discount, 2)

    def __str__(self):
        return self.ProductName

class Transaction(models.Model):
    TransactionID = models.AutoField(primary_key=True)
    UserID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ProductID = models.ForeignKey(Product, on_delete=models.CASCADE)
    Quantity = models.IntegerField(default=0)

    def __str__(self):
        return str(self.TransactionID)

class Order(models.Model):
    UserID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ProductID = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True)
    Quantity = models.IntegerField(default=0)

    def get_price(self):
        if self.ProductID.Discount == 0:
            return round(self.ProductID.Price, 2)
        else:
            return round(self.ProductID.Price - self.ProductID.Discount, 2)

    def total_price(self):
        if self.ProductID.Discount is None:
            return round(self.ProductID.Price * self.Quantity, 2)
        else:
            return round((self.ProductID.Price - self.ProductID.Discount) * self.Quantity, 2)

    def __str__(self):
        return str(self.ProductID)

class Cart(models.Model):
    CartID = models.AutoField(primary_key=True)
    UserID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    TotalQuantity = models.IntegerField(default=0)

    def __str__(self):
        return str(self.CartID)

    
    
class Profile(models.Model):
    UserID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100)
    LastName = models.CharField(max_length=100)
    CardID = models.CharField(max_length=100)
    Address = models.CharField(max_length=100)
    Country = CountryField()
    

    def __str__(self):
        return str(self.UserID)

items/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column
from django_countries.fields import CountryField

CATEGORIES = (
        ('T', 'Technology'),
        ('C', 'Comedy'),
        ('A', 'Adventure'),
        ('H', 'Horror'),
        ('R', 'Romance'),
        ('O', 'Other'),
        ('M', 'Mystery')
)


class AddToCartForm(forms.Form):
    pass

class UserProfileForm(forms.Form):
    Name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    LastName = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    CardID = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    Address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    Country = CountryField(blank_label=('Select Country')).formfield(attrs={
        'class': 'custom-select d-block w-100'
    })

class InsertProductForm(forms.Form):
    ProductName = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    Price = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    Discount = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }), initial=0)
    Description = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control'
    }))
    Image = forms.ImageField(required=False, initial='default.png')
    Stock = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }))
    slug = forms.SlugField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    ProductType = forms.ChoiceField(choices=CATEGORIES)

class Filter(forms.Form):
    Technology = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check1'
    }), required=False)
    Comedy = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check2'
    }), required=False)
    Adventure = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check3'
    }), required=False)
    Horror = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check4'
    }), required=False)
    Romance = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check5'
    }), required=False)
    Other = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check6'
    }), initial=True, required=False)
    Mystery = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input',
        'onclick':'this.form.submit();',
        'id': 'check7'
    }), initial=True, required=False)


    

items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.db.models import Sum
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, Transaction, Cart, Order, Profile
from .forms import UserProfileForm, InsertProductForm, Filter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

class Home(View):
      
    categories = ['Technology', 'Comedy', 'Adventure', 'Horror', 'Romance', 'Other', 'Mystery']
    visible = {'Technology': True, 'Comedy': True, 'Adventure': True, 'Horror': True, 'Romance': True, 'History': True, 'Mystery': True}
    choices = ('T', 'C', 'A', 'H', 'R', 'O', 'M',)

    def get(self, request, *args, **kwargs):

        if 'visible' not in request.session:
            request.session['visible'] = {'Technology': True, 'Comedy': True, 'Adventure': True, 'Horror': True, 'Romance': True, 'History': True, 'Mystery': True}
        
        if 'choices' not in request.session:
            request.session['choices'] = ('T', 'C', 'A', 'H', 'R', 'O', 'M',)

        choices = request.session['choices']
        visible = request.session['visible']

        model = Product.objects.filter(ProductType__in=choices)
        
        paginator = Paginator(model, 4)

        page = request.GET.get('page', 1)
        try :
            offset = paginator.page(page)
        except PageNotAnInteger:
            offset = paginator.page(1)
        except EmptyPage:
            offset = paginator.page(paginator.num_pages)

        form = Filter(request.POST or None, initial=visible)
        context = {
            'form': form,
            'page_obj': offset,
        }
        return render(self.request, "home.html", context=context)

    def post(self, request, *args, **kwargs):
        
        visible = request.session['visible']
        choices=()
        form = Filter(request.POST)
        if request.method == 'POST':
            if form.is_valid():
                for category in self.categories:
                    if not category in request.POST:
                        visible[category] = False
                    else:
                        choices += (category[0],)
                        visible[category] = True
                print(self.choices)

                form = Filter(request.POST, initial=visible)
                model = Product.objects.filter(ProductType__in=choices)
                paginator = Paginator(model, 4)

                request.session['visible'] = visible
                request.session['choices'] = choices

                page = request.GET.get('page', 1)
                try :
                    offset = paginator.page(page)
                except PageNotAnInteger:
                    offset = paginator.page(1)
                except EmptyPage:
                    offset = paginator.page(paginator.num_pages)
                
                context = {
                    'form': form,
                    'page_obj': offset,
                }
                return render(self.request, "home.html", context=context)
        
        return redirect('items:home') 

class Details(DetailView):
    model = Product
    template_name = "product.html"

class CartSummary(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            order = Order.objects.filter(UserID=request.user)
            total = 0
            for product in order:
                total += product.total_price()

            context = {
                'object': order,
                'total': total
                }

            return render(self.request, "cart_summary.html", context=context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have any order")
            return redirect("/")

class Checkout(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        profile = Profile.objects.filter(UserID=request.user)
        if profile.exists():
            try:
                order = Order.objects.filter(UserID=request.user)
            
                total = 0
                for product in order:
                    total += product.total_price()

                context = {
                    'profile': profile,
                    'object': order,
                    'total': total
                }
                return render(self.request, "checkout.html", context=context)

            except ObjectDoesNotExist:
                return redirect("/")
        else:
            return redirect("items:profile")
        

@login_required
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    
    cartList = Cart.objects.filter(UserID=request.user)
    orderList = Order.objects.filter(UserID=request.user, ProductID=product.ProductID)

    if cartList.exists():
            cart = cartList[0]
            cart.TotalQuantity += 1
            if orderList.exists():
                order = orderList[0]
                order.Quantity += 1
                if order.Quantity <= product.Stock:
                    order.save()
                    cart.save()
            else:
                Order.objects.create(UserID=request.user, ProductID=product, Quantity=1)
                cart.save()
    else:
        Order.objects.create(UserID=request.user, ProductID=product, Quantity=1)
        Cart.objects.create(UserID=request.user, TotalQuantity=1)

    return redirect("items:cart_summary")


@login_required
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    
    cartList = Cart.objects.filter(UserID=request.user)
    orderList = Order.objects.filter(UserID=request.user, ProductID=product.ProductID)

    if cartList.exists():
        if orderList.exists():
            order = orderList[0]
            if order.Quantity > 1:
                order.Quantity -= 1
                order.save()
            else:
                order.delete()
            cart = cartList[0]
            cart.TotalQuantity -= 1
            cart.save()

    return redirect("items:cart_summary")


@login_required
def remove_row(request, slug):
    product = get_object_or_404(Product, slug=slug)
    
    cartList = Cart.objects.filter(UserID=request.user)
    orderList = Order.objects.filter(UserID=request.user, ProductID=product.ProductID)

    if cartList.exists():
        if orderList.exists():
            order = orderList[0]
            cart = cartList[0]
            cart.TotalQuantity -= order.Quantity
            cart.save()
            order.delete()

    return redirect("items:cart_summary")




class UserProfile(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        checkProfile = Profile.objects.filter(UserID=request.user)
        if checkProfile.exists():
            form = UserProfileForm(initial={
                'Name': checkProfile[0].Name,
                'LastName': checkProfile[0].LastName,
                'CardID': checkProfile[0].CardID,
                'Address': checkProfile[0].Address,
                'Country': checkProfile[0].Country,
                })
        else:
            form = UserProfileForm()

        context = {
            'form': form
        }
        return render(self.request, "profile.html", context=context)
    
    def post(self, request, *args, **kwargs):
        form = UserProfileForm(self.request.POST or None)
        if form.is_valid():
            checkProfile = Profile.objects.filter(UserID=request.user)
            Name = form.cleaned_data.get('Name')
            LastName = form.cleaned_data.get('LastName')
            CardID = form.cleaned_data.get('CardID')
            Address = form.cleaned_data.get('Address')
            Country = form.cleaned_data.get('Country')
            if checkProfile.exists():
                checkProfile.delete()
            Profile.objects.create(UserID=request.user, Name=Name, LastName=LastName, Address=Address, CardID=CardID, Country=Country)
            return redirect('items:home')

        form = UserProfileForm()
        context = {
            'form': form
        }

        return render(self.request, "profile.html", context=context)



class AddProduct(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = InsertProductForm(self.request.POST, self.request.FILES)
        context = {
            'form': form,
            'valid': 'true'
        }
        return render(self.request, "add_product.html", context=context)


    def post(self, request, *args, **kwargs):
        form = InsertProductForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            slug = form.cleaned_data.get('slug')
            checkSlug = Product.objects.filter(slug=slug)
            if checkSlug.exists():
                context = {
                    'form': form,
                    'valid': 'false'
                }
                return render(self.request, "add_product.html", context=context)
            else:
                ProductName = form.cleaned_data.get('ProductName')
                Price = form.cleaned_data.get('Price')
                Discount = form.cleaned_data.get('Discount')
                Description = form.cleaned_data.get('Description')
                Image = form.cleaned_data.get('Image')
                Stock = form.cleaned_data.get('Stock')
                slug = form.cleaned_data.get('slug')
                ProductType = form.cleaned_data.get('ProductType')
                Product.objects.create(ProductName=ProductName, Price=Price, Discount=Discount,
                            Description=Description, Image=Image, Stock=Stock,
                            slug=slug, ProductType=ProductType, UserID=request.user)

items/templates/cart_summary.html
{% load static %}
{% load quantity %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>E-book</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'eshop/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'eshop/css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'eshop/css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header {
      height: 100%;
      margin: 0;
      padding: 0;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    .table {

      margin-top: 80px;

    }

    footer {
      margin-top: 80px !important;
    }


    .navbar {
      background-color: rgb(200, 200, 200);
    }
  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
        <strong class="blue-text">e-Book</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:profile' %}">Edit Profile
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:add_product' %}">Add Product
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user|products_in_cart}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_logout' %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              Log out
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> 0 </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_signup' %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              Signup
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_login' %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              Log in
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <!--Main layout-->
  <main>
    <div class="container">

      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Price</th>
            <th scope="col">Deletion</th>
          </tr>
        </thead>
        <tbody>
          {% for item in object %}
          <tr>
            <th scope="row">{{item.ProductID}}</th>
            <td>{{item.get_price}}</td>
            <td> <a href="{% url 'items:remove_from_cart' item.ProductID.slug %}"><span>&#8722;</span></a>
              {{item.Quantity}} <a href="{% url 'items:cart' item.ProductID.slug %}"><span>&#43;</span></a> </td>
            <td>{{item.total_price}}</td>
            <td><a href="{% url 'items:remove_row' item.ProductID.slug %}"><i class="fa fa-trash"></i></a></td>
          </tr>


          </tr>

          {% endfor %}
          <tr>
            <td colspan="4">Total Price</td>
            <td>{{total}}</td>
          </tr>
        </tbody>
      </table>

      {% if request.user|products_in_cart != 0 %}
      <tr>
        <td colspan="5"><a href="{% url 'items:checkout' %}" class="btn btn-success float-right">Checkout</a></td>
      </tr>
      {% endif %}

    </div>
  </main>
  <!--Main layout-->
  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'eshop/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'eshop/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'eshop/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'eshop/js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

items/templates/product.html
{% load static %}
{% load quantity %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>e-Book</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'eshop/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'eshop/css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'eshop/css/style.min.css' %}" rel="stylesheet">



</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'items:home' %}" target="_blank">
        <strong class="blue-text">e-Book</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:profile' %}">Edit Profile
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:add_product' %}">Add Product
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'items:cart_summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user|products_in_cart}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_logout' %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              Log out
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'items:cart_summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> 0 </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_signup' %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              Signup
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_login' %}" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              Login
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <!--Main layout-->
  <main class="mt-5 pt-4" style="margin-bottom: 100px;">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.Image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">
            <p class="lead font-weight-bold">{{ object.ProductName }}</p>
            <p class="lead">
              {% if object.Discount %}
              <span class="mr-1">
                <del>{{object.Price}}€</del>
                <span>{{object.get_final_price}}€</span>
              </span>
              {% else %}
              <span>{{object.Price}}€</span>
              {% endif %}
            </p>

            <form class="d-flex justify-content-left">
              <a href="{{ object.get_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

            </form>

            <p class="lead font-weight-bold" style="margin-top: 20px;">Stock: {{ object.Stock }}</p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.Description}}</p>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer fixed-bottom text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!--Copyright-->
    <div class="footer-copyright py-3">

    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->



  </script>
</body>

</html>